[project]
name = "voc-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
]
